version: '3'

services:
  elasticsearch:
    image: elasticsearch:5.5.2
    environment:
      - cluster.name=docker-cluster
    volumes:
      - ./elasticsearch/data/esdata1:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  kibana:
    image: kibana:5.5.2
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - esnet
    depends_on:
      - elasticsearch
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
networks:
  esnet:
    driver: bridge
